version: '3'

services:
  app:
    container_name: picture-frame
    build:
      context: ./next-app
      dockerfile: Dockerfile

    # # Set environment variables directly in the docker-compose file
    # environment:
    #   ENV_VARIABLE: ${ENV_VARIABLE}
    #   NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # # Set envrionment variables based on the .env file
    # env_file:
    #   - .env
    volumes:
      - ./next-app/src:/app/src
      - ./next-app/public:/app/public
      - ./next-app/package.json:/app/package.json
      - ./next-app/yarn.lock:/app/yarn.lock
    restart: always
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - picture-frame

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  picture-frame:
    external: true