version: '3'

services:
  app:
    build: ./
    volumes:
      - ./next-app:/usr/app/picture-frame
    command: sh -c "yarn dev"
    ports:
      - "3000:3000"

  # front:
  #   build: .
  #   volumes:
  #     - .:/myapp
  #   environment:
  #     NODE_ENV: development
  #   ports:
  #     - 3000:3000
  #     # 以下追記
  #     - 9229:9229